# aarch64-linux-gnu 交叉编译工具链文件
# 用法: cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-aarch64.cmake ..

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# 交叉编译工具链前缀
set(CROSS_COMPILE_PREFIX aarch64-linux-gnu-)

# 设置编译器
set(CMAKE_C_COMPILER ${CROSS_COMPILE_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${CROSS_COMPILE_PREFIX}g++)
set(CMAKE_AR ${CROSS_COMPILE_PREFIX}ar)
set(CMAKE_RANLIB ${CROSS_COMPILE_PREFIX}ranlib)
set(CMAKE_STRIP ${CROSS_COMPILE_PREFIX}strip)

# 设置查找路径策略
# ONLY: 只在 CMAKE_FIND_ROOT_PATH 中查找
# NEVER: 不在 CMAKE_FIND_ROOT_PATH 中查找，使用主机路径
# BOTH: 两者都查找
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)  # 允许查找主机头文件（Boost等纯头文件库）
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# 标记为交叉编译
set(CROSS_COMPILING_AARCH64 TRUE)
